#------------------------------------------------------------------------------
# Base Infrastructure Module Outputs
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# URLs
#------------------------------------------------------------------------------
output "cloudfront_distribution_domain_name" {
  description = "CloudFront distribution domain name"
  value       = module.cloudfront.distribution_domain_name
}

output "alb_dns_name" {
  description = "ALB DNS name (direct API access, internal use only)"
  value       = module.alb.alb_dns_name
}

#------------------------------------------------------------------------------
# Resource ARNs / IDs
#------------------------------------------------------------------------------
output "ecr_repository_url" {
  description = "ECR repository URL for docker push"
  value       = module.ecr.repository_url
}

output "ecs_cluster_name" {
  description = "ECS cluster name"
  value       = module.ecs.cluster_name
}

output "ecs_service_name" {
  description = "ECS service name"
  value       = module.ecs.service_name
}

output "rds_cluster_endpoint" {
  description = "RDS cluster endpoint"
  value       = module.rds.cluster_endpoint
  sensitive   = true
}

output "s3_bucket_name" {
  description = "S3 bucket for frontend deployment"
  value       = module.cloudfront.s3_bucket_name
}

output "cloudfront_distribution_id" {
  description = "CloudFront distribution ID"
  value       = module.cloudfront.distribution_id
}

#------------------------------------------------------------------------------
# Secrets ARNs (for CI/CD)
#------------------------------------------------------------------------------
output "db_password_secret_arn" {
  description = "ARN of database credentials secret"
  value       = module.secrets.db_password_secret_arn
  sensitive   = true
}

output "api_token_secret_arn" {
  description = "ARN of API token secret"
  value       = module.secrets.api_token_secret_arn
  sensitive   = true
}

#------------------------------------------------------------------------------
# Network Information
#------------------------------------------------------------------------------
output "vpc_id" {
  description = "VPC ID"
  value       = module.network.vpc_id
}

output "private_subnet_ids" {
  description = "Private subnet IDs"
  value       = module.network.private_subnet_ids
}

#------------------------------------------------------------------------------
# Monitoring
#------------------------------------------------------------------------------
output "ecs_cpu_alarm_arn" {
  description = "ECS CPU alarm ARN"
  value       = module.cloudwatch.ecs_cpu_alarm_arn
}

output "ecs_memory_alarm_arn" {
  description = "ECS memory alarm ARN"
  value       = module.cloudwatch.ecs_memory_alarm_arn
}

output "alb_5xx_alarm_arn" {
  description = "ALB 5xx errors alarm ARN"
  value       = module.cloudwatch.alb_5xx_alarm_arn
}

#------------------------------------------------------------------------------
# Cognito
#------------------------------------------------------------------------------
output "cognito_user_pool_id" {
  description = "Cognito User Pool ID"
  value       = module.cognito.user_pool_id
}

output "cognito_user_pool_arn" {
  description = "Cognito User Pool ARN"
  value       = module.cognito.user_pool_arn
}

output "cognito_client_id" {
  description = "Cognito App Client ID"
  value       = module.cognito.client_id
}

output "cognito_domain" {
  description = "Cognito Hosted UI domain"
  value       = module.cognito.domain
}

output "cognito_issuer" {
  description = "Cognito Issuer URL (for JWT validation)"
  value       = module.cognito.issuer
}

output "cognito_jwks_uri" {
  description = "JWKS URI for JWT verification"
  value       = module.cognito.jwks_uri
}

output "cognito_frontend_config" {
  description = "Configuration object for frontend .env"
  value       = module.cognito.frontend_config
}

#------------------------------------------------------------------------------
# Environment Configuration Outputs (for .env files)
#------------------------------------------------------------------------------
output "api_env_config" {
  description = "Environment variables for API .env file"
  value       = <<-EOT
    # API Environment Configuration
    # Generated by Terraform - Copy to apps/api/.env

    # Server
    PORT=8080
    NODE_ENV=production
    TZ=Asia/Tokyo

    # Database (retrieve password from Secrets Manager)
    # aws secretsmanager get-secret-value --secret-id ${module.secrets.db_password_secret_arn} --query SecretString --output text
    DATABASE_URL=postgresql://${var.db_username}:<DB_PASSWORD>@${module.rds.cluster_endpoint}:5432/${var.db_name}

    # Cognito (JWT Authentication)
    COGNITO_ISSUER=${module.cognito.issuer}
    COGNITO_CLIENT_ID=${module.cognito.client_id}
    COGNITO_JWKS_URI=${module.cognito.jwks_uri}

    # CORS
    CORS_ALLOWED_ORIGINS=https://${module.cloudfront.distribution_domain_name}

    # Logging
    LOG_LEVEL=info
  EOT
}

output "web_env_config" {
  description = "Environment variables for Web .env file"
  value       = <<-EOT
    # Web Environment Configuration
    # Generated by Terraform - Copy to apps/web/.env

    # API
    VITE_API_URL=https://${module.cloudfront.distribution_domain_name}

    # Timezone
    VITE_TIMEZONE=Asia/Tokyo

    # Cognito Authentication
    VITE_COGNITO_USER_POOL_ID=${module.cognito.user_pool_id}
    VITE_COGNITO_CLIENT_ID=${module.cognito.client_id}
    VITE_COGNITO_DOMAIN=${module.cognito.domain}
    VITE_COGNITO_REDIRECT_URI=https://${module.cloudfront.distribution_domain_name}/auth/callback
    VITE_COGNITO_LOGOUT_URI=https://${module.cloudfront.distribution_domain_name}/login
    VITE_COGNITO_SCOPE=openid email profile
  EOT
}

output "db_password_retrieval_command" {
  description = "Command to retrieve database password from Secrets Manager"
  value       = "aws secretsmanager get-secret-value --secret-id ${module.secrets.db_password_secret_arn} --query SecretString --output text | jq -r .password"
}
